runtime: java17
instance_class: F2
service: newbkend

env_variables:
  WORKDIR: 'springapp'
  SPRING_PROFILES_ACTIVE: "prod"

entrypoint: java -jar target/app.jar

handlers:
  - url: /.*
    script: auto
